# Generated by Django 4.2.3 on 2023-10-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_paymentterms_cid"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentterms",
            name="cid",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.company",
            ),
        ),
    ]
