# Generated by Django 4.2.3 on 2023-10-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_salesorder_cheque_no_salesorder_complete_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesorder", old_name="complete_status", new_name="inv_status",
        ),
        migrations.AddField(
            model_name="salesorder",
            name="salcrd_status",
            field=models.IntegerField(default=0),
        ),
    ]
