# Generated by Django 4.2.3 on 2023-10-23 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_salesorder_balance_salesorder_paidoff"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="term_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.paymentterms",
            ),
        ),
    ]
