# Generated by Django 3.2.22 on 2023-10-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_mjournal_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='e_waybills',
            fields=[
                ('ewbillid', models.AutoField(primary_key=True, serialize=False, verbose_name='ewid')),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('document_type', models.CharField(max_length=200, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.EmailField(max_length=254, null=True)),
                ('gsttype', models.CharField(max_length=100, null=True)),
                ('gstin', models.CharField(default='', max_length=100)),
                ('transaction_subtype', models.CharField(max_length=200, null=True)),
                ('transaction_type', models.CharField(choices=[('Goods', 'Goods'), ('Service', 'Service')], max_length=150, null=True)),
                ('transaction_hsn', models.IntegerField(blank=True, default=0, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('placeof_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(max_length=100, null=True)),
                ('kilometer', models.FloatField(null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('igst', models.FloatField(blank=True, null=True)),
                ('cgst', models.FloatField(blank=True, null=True)),
                ('sgst', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('shipping_charge', models.FloatField(blank=True, null=True)),
                ('adjustment', models.FloatField(blank=True, default=0, null=True)),
                ('grand_total', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(null=True)),
                ('file', models.FileField(default='default.png', upload_to='purchase/ewbill')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Billed', 'Billed')], default='Draft', max_length=150)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('transportation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='e_waybill_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, null=True)),
                ('hsn', models.CharField(max_length=100, null=True)),
                ('qty', models.IntegerField(default=0, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('tax', models.CharField(max_length=100, null=True)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.e_waybills')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
