# Generated by Django 4.2.3 on 2023-10-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_salesorder_term_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="salesorder", name="term_id",),
        migrations.AddField(
            model_name="salesorder",
            name="term_days",
            field=models.IntegerField(null=True),
        ),
    ]
