# Generated by Django 4.2.3 on 2023-10-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_remove_salesorder_term_id_salesorder_term_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="adjust",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
