# Generated by Django 3.2.22 on 2023-10-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20231012_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_transaction',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
