# Generated by Django 3.2.22 on 2023-10-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_bankings_g_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, default='Present', max_length=100, null=True),
        ),
    ]
