# Generated by Django 4.2.3 on 2023-10-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_customer_convert_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="convert_status", new_name="convert_crd",
        ),
        migrations.AddField(
            model_name="customer",
            name="convert_inv",
            field=models.IntegerField(default=0),
        ),
    ]
