# Generated by Django 4.2.3 on 2023-10-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_rename_convert_status_customer_convert_crd_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="convert_crd",),
        migrations.RemoveField(model_name="customer", name="convert_inv",),
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.FloatField(null=True),
        ),
    ]
